/**
 * DotHunter — App.js
 *
 * FIX (blank screen on Android):
 *   Previously the app used Asset.fromModule() + FileSystem.readAsStringAsync()
 *   to load game.html at runtime. On production Android builds this async read
 *   can silently fail, leaving htmlContent === null and the WebView never mounts.
 *
 *   The fix: gameHtml.js inlines the entire HTML as a plain JS string constant.
 *   Metro bundles it directly into the JS bundle — no runtime filesystem access,
 *   no async loading, no silent failures. Works on every Android version.
 */

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  StatusBar,
  Animated,
  Easing,
  Platform,
} from 'react-native';
import { WebView } from 'react-native-webview';

// ── Inlined game HTML (generated by generate_game_js.py from assets/web/game.html)
// This is a plain string bundled by Metro — no async file I/O needed at runtime.
import GAME_HTML_STRING from './gameHtml';

// ─── Constants ────────────────────────────────────────────────────────────────
const BG_COLOR          = '#0a0a1a';   // Game's dark background
const ACCENT            = '#00E5FF';   // Game's primary neon accent (cyan)
const ACCENT_DIM        = '#00E5FF33'; // Translucent glow layer
const SPLASH_DURATION_MS = 2500;       // How long the splash is fully visible
const FADE_IN_MS         = 600;        // Entrance animation duration
const FADE_OUT_MS        = 400;        // Exit animation duration

// Android WebView needs this base URL so that relative resources inside the
// inline HTML can resolve correctly against the APK asset folder.
const WEBVIEW_BASE_URL = Platform.OS === 'android'
  ? 'file:///android_asset/'
  : '';

// ─── SplashScreen Component ───────────────────────────────────────────────────
function SplashScreen({ onFinished }) {
  const titleOpacity  = React.useRef(new Animated.Value(0)).current;
  const titleScale    = React.useRef(new Animated.Value(0.88)).current;
  const dotOpacity    = React.useRef(new Animated.Value(0)).current;
  const dotScale      = React.useRef(new Animated.Value(0.6)).current;
  const screenOpacity = React.useRef(new Animated.Value(1)).current;

  React.useEffect(() => {
    // Step 1: Dot pulses in
    Animated.parallel([
      Animated.timing(dotOpacity, {
        toValue: 1,
        duration: FADE_IN_MS * 0.6,
        easing: Easing.out(Easing.ease),
        useNativeDriver: true,
      }),
      Animated.spring(dotScale, {
        toValue: 1,
        friction: 5,
        tension: 80,
        useNativeDriver: true,
      }),
    ]).start();

    // Step 2: Title fades + scales in (slight delay)
    Animated.sequence([
      Animated.delay(180),
      Animated.parallel([
        Animated.timing(titleOpacity, {
          toValue: 1,
          duration: FADE_IN_MS,
          easing: Easing.out(Easing.ease),
          useNativeDriver: true,
        }),
        Animated.spring(titleScale, {
          toValue: 1,
          friction: 6,
          tension: 60,
          useNativeDriver: true,
        }),
      ]),
    ]).start();

    // Step 3: After splash duration, fade the whole overlay out
    const exitTimer = setTimeout(() => {
      Animated.timing(screenOpacity, {
        toValue: 0,
        duration: FADE_OUT_MS,
        easing: Easing.in(Easing.ease),
        useNativeDriver: true,
      }).start(() => onFinished());
    }, SPLASH_DURATION_MS);

    return () => clearTimeout(exitTimer);
  }, []);

  return (
    <Animated.View style={[styles.splashContainer, { opacity: screenOpacity }]}>
      <StatusBar barStyle="light-content" backgroundColor={BG_COLOR} />

      {/* Ambient glow ring */}
      <Animated.View
        style={[styles.glowRing, { opacity: dotOpacity, transform: [{ scale: dotScale }] }]}
      />

      {/* Neon dot icon */}
      <Animated.View
        style={[styles.dotIcon, { opacity: dotOpacity, transform: [{ scale: dotScale }] }]}
      />

      {/* ── VIDEO_PLACEHOLDER — drop video asset here ──────────────────────────
       *
       *  To add an intro video, replace this comment block with:
       *
       *    import { Video, ResizeMode } from 'expo-av';
       *
       *    <Video
       *      source={require('./assets/intro.mp4')}
       *      style={styles.splashVideo}
       *      resizeMode={ResizeMode.COVER}
       *      shouldPlay
       *      isLooping={false}
       *      isMuted={false}
       *      onPlaybackStatusUpdate={(status) => {
       *        if (status.didJustFinish) onFinished();
       *      }}
       *    />
       *
       *  Also install: npx expo install expo-av
       *  And remove the setTimeout-based exit in the useEffect above.
       *
       * ─────────────────────────────────────────────────────────────────────── */}

      {/* Game title */}
      <Animated.View
        style={{ opacity: titleOpacity, transform: [{ scale: titleScale }], alignItems: 'center', marginTop: 28 }}
      >
        <Text style={styles.titleDot}>●</Text>
        <Text style={styles.titleMain}>DOT HUNTER</Text>
        <Text style={styles.titleSub}>focus · reflex · speed</Text>
      </Animated.View>
    </Animated.View>
  );
}

// ─── Root App Component ───────────────────────────────────────────────────────
export default function App() {
  const [splashDone, setSplashDone] = React.useState(false);

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor={BG_COLOR} />

      {/*
       * WebView — always mounted immediately (no async loading gate).
       * GAME_HTML_STRING is a plain JS string bundled by Metro, so it is
       * available synchronously on first render — no blank screen, ever.
       *
       * Key props for Android compatibility:
       *   originWhitelist={['*']}              — allow all origins in inline HTML
       *   allowFileAccess={true}               — allow file:// URIs
       *   allowUniversalAccessFromFileURLs     — allow XHR from file:// context
       *   mixedContentMode="always"            — allow mixed http/https content
       *   baseUrl (android_asset)              — correct base for relative paths
       */}
      <WebView
        originWhitelist={['*']}
        source={{ html: GAME_HTML_STRING, baseUrl: WEBVIEW_BASE_URL }}
        style={styles.webview}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        allowFileAccess={true}
        allowUniversalAccessFromFileURLs={true}
        mixedContentMode="always"
        allowsInlineMediaPlayback={true}
        mediaPlaybackRequiresUserAction={false}
        scrollEnabled={false}
        bounces={false}
        overScrollMode="never"
        setBuiltInZoomControls={false}
        setDisplayZoomControls={false}
        scalesPageToFit={false}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        cacheEnabled={true}
        textZoom={100}
      />

      {/* Splash overlay — sits on top until animation completes */}
      {!splashDone && (
        <SplashScreen onFinished={() => setSplashDone(true)} />
      )}
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BG_COLOR,
  },
  webview: {
    flex: 1,
    backgroundColor: BG_COLOR,
  },
  splashContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: BG_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  glowRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: ACCENT_DIM,
    marginTop: -20,
  },
  dotIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: ACCENT,
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 20,
    elevation: 12,
  },
  titleDot: {
    fontSize: 18,
    color: ACCENT,
    marginBottom: 6,
    textShadowColor: ACCENT,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  titleMain: {
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: 6,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  titleSub: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 4,
    color: '#FFFFFF55',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
});
